# Generated by Django 2.2.3 on 2019-07-28 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='body',
            field=models.TextField(verbose_name='İçerik'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='check',
            field=models.BooleanField(null=True, verbose_name='Tamamlandı'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Başlık'),
        ),
    ]
