# Generated by Django 2.2.3 on 2019-07-31 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_auto_20190728_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='body',
        ),
        migrations.AlterField(
            model_name='todo',
            name='check',
            field=models.BooleanField(default=False, verbose_name='Tamamlandı'),
        ),
    ]
