# Generated by Django 2.2.3 on 2019-07-31 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_auto_20190731_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='check',
            field=models.BooleanField(verbose_name='Tamamlandı'),
        ),
    ]
