# Generated by Django 2.2.3 on 2019-07-31 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0004_auto_20190731_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='check',
            field=models.BooleanField(null=True, verbose_name='Tamamlandı'),
        ),
    ]
