# Generated by Django 2.2.3 on 2019-07-31 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0005_auto_20190731_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='check',
            field=models.BooleanField(default=True, verbose_name='Tamamlandı'),
            preserve_default=False,
        ),
    ]
