# Generated by Django 2.2.3 on 2019-08-01 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0010_auto_20190731_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='date',
        ),
    ]
